name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Deploy whenever code is pushed to the master branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Replace with the Node.js version supported by your project

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build # This will now handle both the build and static export

      - name: Disable Jekyll
        run: echo "" > ./out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # The `out` directory will be automatically created
